mkdir -p ~/.sources
wget https://raw.githubusercontent.com/siphu/UsefulBashAlias/main/sources/files -O ~/.sources/files

echo "# Auto generated by UsefulBashAlias" > ~/.bash_profile
echo ". ~/.sources/files" > ~/.bash_profile

. ~/.bash_profile
