mkdir -p ~/.sources
wget https://raw.githubusercontent.com/siphu/UsefulBashAlias/main/sources/files -P ~/.sources

echo "# Auto generated by UsefulBashAlias" > ~/.bash_profile
echo ". ~/.sources/files" > ~/.bash_profile

. ~/.bash_profile
